name: Build with redis
on: [push, pull_request]
jobs:
  job:
    runs-on: ubuntu-latest
    container: node:12
    timeout-minutes: 10
    services:
      redis:
        image: grokzen/redis-cluster
        env: 
          CLUSTER_ONLY: 'true'
          MASTERS: 3
          SLAVES_PER_MASTER: 1
        options: >-
          --health-cmd "redis-cli --cluster call <ip>:<port> INFO"
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - uses: actions/checkout@v1