name: Build with dynamo
on: [push, pull_request]
jobs:
  job:
    runs-on: ubuntu-latest
    container: node:12
    timeout-minutes: 10
    services:        
      dynamodb-local:
        image: amazon/dynamodb-local:1.16.0
        ports:
        - 8000:8000
        options: --workdir /home/dynamodblocal --health-cmd "curl --fail http://127.0.0.1:8000/shell/ || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      
      - name: Install docker
        run: |
          apt-get update 
          apt-get install \
          ca-certificates \
          curl \
          gnupg \
          lsb-release -y
          curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null  
          apt-get update 
          apt-get install docker-ce docker-ce-cli containerd.io -y
          docker --version
          docker run -p 8001:8001 amazon/dynamodb-local & 
        
          
